name: Build Automatizado

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Versao java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Build do projeto
        run: mvn clean package

      - name: Build Imagem Docker
        run: docker build -t vivianepecenin/com6bankwar .

      - name: Push Imagem Docker
        run: docker push vivianepecenin/com6bankwar