name: Build Automatizado

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    environment: com6bank
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Versao java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Build do projeto
        run: mvn clean package

      - name: Build Imagem Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          context: /home/runner/work/Com6bankWar
          file: Dockerfile
          tags: vivianepecenin/com6bank:latest
        
      - name: Push Imagem Docker
        run: docker push vivianepecenin/com6bankwar
