name: Build Automatizado

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOUCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      JWT_SECRET: secret

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Versao java
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Build do projeto
        run: mvn clean package

      - name: Build Imagem Docker
        run: docker build -t vivianepecenin/com6bankwar .
        env:
          MYSQL_HOST: mysql

      - name: Push Imagem Docker
        run: docker push vivianepecenin/com6bankwar